### PR TITLE
Make rooms argument a list of room ids

### PR DESCRIPTION
**Pull request by lordievader**
Ensure the documentation is in line with the code. Modify the code to
expect a list of room ids rather than room objects.
Additionally, ensure the invite handler checks if the room invite comes
from a room in the whitelist, if given.

### CODE REVIEW

**Comment by shawnanastasio** [comment]
Thanks for the PR. Accepting room ids seems like a better choice, but I'm concerned about breaking the API for existing consumers that pass it room objects (are there any?)

Maybe a better approach would be to determine the type of each element of the `rooms` list to determine whether an ID or Room object is passed and handle both.

**Comment by lordievader** [comment]
Hadn't thought of that. Good solution will add it to the PR.

**Comment by lordievader** [comment]
Updated the PR. If the `room` is a string it is assumed to be a room_id, otherwise it follows the previous behavior.

Besides, I've updated the `self.rooms` list in case of setting `rooms` to None, it is now a list of room objects. Like it is when `rooms` is not None. `self.room_ids` is now used for the list of room_ids.

**Comment by shawnanastasio** [comment]
One small issue, line 29 now fails if `None` is passed in for `rooms` since it is treated as a list later on. Something like this is needed to fix that:
```
        self.room_ids = rooms if rooms else []
```

But after testing with the fix applied, I'm unable to get the string room id feature to work. I passed in the full room ID of a test room that the bot is already in (something like "!\<unique id>:\<server url>") and the bot initializes fine but doesn't respond to any messages. Is there a specific room syntax that needs to be passed in to the underlying matrix_client API, or is this a logic bug (i.e. calling `self.client.join_room` on an already-joined room)?

**Comment by lordievader** [comment]
> One small issue, line 29 now fails if `None` is passed in for `rooms` since it is treated as a list later on. Something like this is needed to fix that:
Ah, quite right. I fixed it with:
> ```
>         self.room_ids = []
> ```
Since room_ids are added after joining them in both cases.

> But after testing with the fix applied, I'm unable to get the string room id feature to work. I passed in the full room ID of a test room that the bot is already in (something like "!<unique id>:<server url>") and the bot initializes fine but doesn't respond to any messages. Is there a specific room syntax that needs to be passed in to the underlying matrix_client API, or is this a logic bug (i.e. calling `self.client.join_room` on an already-joined room)?
I cannot reproduce this. You could import `pdb` and add `pdb.set_trace()` as the first line of the `handle_message` function. That way for every message the bot gets it will start a debug shell (kind of like the interactive python shell).
Honestly, I don't know how the matrix-python-sdk (or the Matrix API) handles joining a room twice.

**Comment by shawnanastasio** [comment]
Ok well since this doesn't break any existing functionality and the behavior I'm observing might not be reproducible, I'll merge this.

**Pull request merged**
